#!/usr/bin/env ruby
require 'find'
require 'rubbish'

# ruby -c
Find.find('./lib') do |fn|
  if fn=~/\.rb$/
    print "#{fn}:\t"
    unless system "ruby -c #{fn}"
      exit 1
    end
  end
end

# VERSION
_,MAJOR,MINOR,BUILD = `egrep "VERSION = '[0-9]+\\.[0-9]+\\.[0-9]+'" lib/*.rb`.split(/\D+/)
unless MAJOR and MINOR and BUILD
  puts "Could not get VERSION."
  exit 1
end

# BUILD
newest = Rubbish.fish('ls -t lib/**.rb | head -1').strip
build = File.mtime(newest).strftime('%y%m%d')
unless BUILD.start_with? build
  puts "Unexpected BUILD(#{BUILD}) !start_with?(#{build})"
  exit 1
end

# Copyright
year = Time.now.year
author = `git config --get user.name`.strip
unless system("egrep -i 'Copyright.*#{year}.*#{author}' README.*")
  puts "Check README's copyright year and author."
  exit 1
end
